In [10]:
import sys
import numpy as np

In [ ]:
#crear arrays numpy

In [16]:
a = np.array([2,3,4])
print(a)
type(a)

[2 3 4]


numpy.ndarray

In [18]:
a.ndim


1

In [19]:
a.shape #un vector de longitud 3

(3,)

In [46]:
a.dtype

dtype('int64')

In [31]:
b = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [32]:
b.ndim

2

In [33]:
b.shape

(2, 3)

In [64]:
x = np.arange(3) #crear un array de una fila 
print(x)

[0 1 2]


In [66]:
y = np.arange(12).reshape(3,4) #creamos el array de una fila y la reformamos a u
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.ones((2))

array([1., 1.])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Probaremos el peso de una lista y array 

In [38]:
c = np.array([2,3,4])
d = [2,3,4]

In [41]:
sys.getsizeof(c)


120

In [40]:
sys.getsizeof(d)

88

In [ ]:
#Ahora probaremos para listas y arrays mas grandes

In [44]:
big_lista = list(range(1000000))
sys.getsizeof(big_lista_lista)

9000112

In [45]:
big_array = np.array(range(1000000))
sys.getsizeof(big_array)

8000096

In [ ]:
#Ahora las rebanadas

In [49]:
matriz_34 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matriz_34)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
matriz_34[0]

array([1, 2, 3, 4])

In [51]:
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
matriz_34[:,2]

array([ 3,  7, 11])

In [ ]:
#ahora los filtros

In [57]:
matriz_32=np.array([[1,2],[3,4],[5,6]])
print(indice_filtrado)

[[1 2]
 [3 4]
 [5 6]]


In [60]:
indice_filtrado = matriz_32 > 2
print(indice_filtrado)

[[False False]
 [ True  True]
 [ True  True]]


In [61]:
matriz_32[indice_filtrado]

array([3, 4, 5, 6])